const fs = require('fs');
const r1 = (s) => s.replace(/-?\d+\.\d+/g, (n) => (+n).toFixed(1).replace(/\.0$/, ''));
const mark = JSON.parse(fs.readFileSync('mark.json'));
const word = JSON.parse(fs.readFileSync('word.json'));
const tag = JSON.parse(fs.readFileSync('tag.json'));
const K = r1(mark[0].s), T = r1(mark[1].s);
const W = r1(word.map((w) => w.s).join(''));
const TAGL = r1(tag.filter((t) => t.x1 - t.x0 < 100).map((t) => t.s).join(''));
const LINES = tag.filter((t) => t.x1 - t.x0 >= 100).map((t) => r1(t.s));
const out = `// KT INDIA brand assets: vector mark and wordmark traced from the supplied logo (potrace),
// split into ribbon pieces so the mark can animate. Generated by scripts/trace-logo (see README).
// Mark viewBox: 420 145 690 600. Wordmark viewBox: 130 788 1200 106.
export const K_PATH = '${K}';
export const T_PATH = '${T}';
export const WORD_PATH = '${W}';
export const TAG_PATH = '${TAGL}';
export const TAG_LINES = ${JSON.stringify(LINES)};

// Colours sampled from the supplied logo.
const STOPS = {
  stem: [['0', '#8efaca'], ['.5', '#44e4d5'], ['1', '#0ac4e7']],
  arm: [['0', '#0790a8'], ['.18', '#14b8cc'], ['.5', '#92f26f'], ['.75', '#adf945'], ['1', '#dcfb7b']],
  leg: [['0', '#0a9fbd'], ['.2', '#12c3e0'], ['.6', '#7af08d'], ['1', '#d9fc6e']],
  fold: [['0', '#107946'], ['1', '#95f145']],
};
const grad = (id, x1, y1, x2, y2, stops) => \`<linearGradient id="\${id}" gradientUnits="userSpaceOnUse" x1="\${x1}" y1="\${y1}" x2="\${x2}" y2="\${y2}">\${stops.map(([o, c]) => \`<stop offset="\${o}" stop-color="\${c}"/>\`).join('')}</linearGradient>\`;

// id: unique prefix per instance on a page. tFill: colour of the white T (use a CSS var inline).
export function markSvg({ id = 'kt', cls = 'kt-mark', tFill = 'var(--logo-t, #edf7f1)', title = '' } = {}) {
  const a11y = title ? \`role="img" aria-label="\${title}"\` : 'aria-hidden="true" focusable="false"';
  return \`<svg class="\${cls}" viewBox="420 145 690 600" width="69" height="60" \${a11y}>
<defs>\${grad(id + 's', 475, 154, 475, 715, STOPS.stem)}\${grad(id + 'a', 527, 480, 1067, 175, STOPS.arm)}\${grad(id + 'l', 545, 480, 970, 735, STOPS.leg)}\${grad(id + 'f', 880, 392, 950, 452, STOPS.fold)}
<clipPath id="\${id}cs"><rect x="400" y="140" width="127" height="610"/></clipPath>
<clipPath id="\${id}ca"><path d="M526 140H1120V246H820L640 405L526 502Z"/></clipPath>
<clipPath id="\${id}cl"><path d="M526 502L640 405L820 246H1120V760H526Z"/></clipPath>
<clipPath id="\${id}ct"><path d="\${T_PATH}"/></clipPath></defs>
<g class="kt-stem"><path clip-path="url(#\${id}cs)" fill="url(#\${id}s)" d="\${K_PATH}"/></g>
<g class="kt-leg"><path clip-path="url(#\${id}cl)" fill="url(#\${id}l)" d="\${K_PATH}"/></g>
<g class="kt-arm"><path clip-path="url(#\${id}ca)" fill="url(#\${id}a)" d="\${K_PATH}"/></g>
<g class="kt-t"><path fill="\${tFill}" d="\${T_PATH}"/><path clip-path="url(#\${id}ct)" fill="url(#\${id}f)" d="M865 389C905 389 950 428 950 462V389Z"/></g>
</svg>\`;
}

export function wordmarkSvg({ cls = 'kt-word', fill = 'currentColor', title = 'Kavaiyatech' } = {}) {
  return \`<svg class="\${cls}" viewBox="130 788 1200 106" width="120" height="11" role="img" aria-label="\${title}"><path fill="\${fill}" d="\${WORD_PATH}"/></svg>\`;
}
`;
fs.writeFileSync('brand.mjs', out);
console.log('bytes', out.length, 'K', K.length, 'T', T.length, 'W', W.length);
